In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/FazlyRabbiBD/Data-Science-Book/master/data-drugs.csv")

In [ ]:
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB
None


drugY    91
drugX    54
drugA    23
drugC    16
drugB    16
Name: Drug, dtype: int64

In [ ]:
df.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [ ]:
df.Sex.value_counts()

M    104
F     96
Name: Sex, dtype: int64

In [ ]:
df.BP.value_counts()

HIGH      77
LOW       64
NORMAL    59
Name: BP, dtype: int64

In [ ]:
df.Cholesterol.value_counts()

HIGH      103
NORMAL     97
Name: Cholesterol, dtype: int64

In [ ]:
bin_age = [0, 19, 29, 39, 49, 59, 69, 80]
category_age = ['<20s', '20s', '30s', '40s', '50s', '60s', '>60s']
df['Age_binned'] = pd.cut(df['Age'], bins=bin_age, labels=category_age)
df_drug = df.drop(['Age'], axis = 1)

In [ ]:
bin_NatoK = [0, 9, 19, 29, 50]
category_NatoK = ['<10', '10-20', '20-30', '>30']
df['Na_to_K_binned'] = pd.cut(df_drug['Na_to_K'], bins=bin_NatoK, labels=category_NatoK)
df = df.drop(['Na_to_K'], axis = 1)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
X = df.drop(["Drug"], axis=1)
y = df["Drug"]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 5)

In [ ]:
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test)

In [ ]:
X_train.head()

Age  Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  \
170   28      1      0        0       0          1                 1   
182   20      1      0        0       1          0                 0   
59    34      0      1        1       0          0                 1   
185   57      1      0        0       0          1                 0   
12    43      0      1        0       1          0                 1   

     Cholesterol_NORMAL  Age_binned_<20s  Age_binned_20s  Age_binned_30s  \
170                   0                0               1               0   
182                   1                0               1               0   
59                    0                0               0               1   
185                   1                0               0               0   
12                    0                0               0               0   

     Age_binned_40s  Age_binned_50s  Age_binned_60s  Age_binned_>60s  \
170               0               0               0                0   
182               0               0               0                0   
59                0               0               0                0   
185               0               1               0                0   
12                1               0               0                0   

     Na_to_K_binned_<10  Na_to_K_binned_10-20  Na_to_K_binned_20-30  \
170                   0                     1                     0   
182                   0                     1                     0   
59                    0                     1                     0   
185                   0                     0                     1   
12                    0                     1                     0   

     Na_to_K_binned_>30  
170                   0  
182                   0  
59                    0  
185                   0  
12                    0

In [ ]:
X_test.head()

Age  Sex_F  Sex_M  BP_HIGH  BP_LOW  BP_NORMAL  Cholesterol_HIGH  \
119   61      1      0        1       0          0                 1   
77    26      1      0        1       0          0                 0   
148   61      1      0        0       1          0                 0   
149   22      0      1        0       1          0                 1   
154   37      0      1        0       1          0                 0   

     Cholesterol_NORMAL  Age_binned_<20s  Age_binned_20s  Age_binned_30s  \
119                   0                0               0               0   
77                    1                0               1               0   
148                   1                0               0               0   
149                   0                0               1               0   
154                   1                0               0               1   

     Age_binned_40s  Age_binned_50s  Age_binned_60s  Age_binned_>60s  \
119               0               0               1                0   
77                0               0               0                0   
148               0               0               1                0   
149               0               0               0                0   
154               0               0               0                0   

     Na_to_K_binned_<10  Na_to_K_binned_10-20  Na_to_K_binned_20-30  \
119                   0                     0                     1   
77                    0                     0                     1   
148                   1                     0                     0   
149                   1                     0                     0   
154                   0                     1                     0   

     Na_to_K_binned_>30  
119                   0  
77                    0  
148                   0  
149                   0  
154                   0

In [ ]:
from imblearn.over_sampling import SMOTE
X_train, y_train = SMOTE().fit_resample(X_train, y_train)

In [ ]:
from sklearn.naive_bayes import CategoricalNB
NBclassifier1 = CategoricalNB()
NBclassifier1.fit(X_train, y_train)

y_pred = NBclassifier1.predict(X_test)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

from sklearn.metrics import accuracy_score
NBAcc1 = accuracy_score(y_pred,y_test)
print('Naive Bayes accuracy is: {:.2f}%'.format(NBAcc1*100)) 

              precision    recall  f1-score   support

       drugA       0.56      1.00      0.71         5
       drugB       0.60      0.75      0.67         4
       drugC       0.67      1.00      0.80         6
       drugX       0.72      0.93      0.81        14
       drugY       0.95      0.58      0.72        31

    accuracy                           0.75        60
   macro avg       0.70      0.85      0.74        60
weighted avg       0.81      0.75      0.75        60

[[ 5  0  0  0  0]
 [ 1  3  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0 13  1]
 [ 3  2  3  5 18]]
Naive Bayes accuracy is: 75.00%
